
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 30 12:20:52 COT 2020
//----------------------------------------------------

package cod;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Mayor_que = 49;
  public static final int Parentesis_c = 5;
  public static final int Parentesis_a = 4;
  public static final int Llave_c = 7;
  public static final int Incremento = 60;
  public static final int Llave_a = 6;
  public static final int Libreria = 71;
  public static final int Linea = 2;
  public static final int Break = 37;
  public static final int Coma = 10;
  public static final int Suma_igual = 55;
  public static final int Corchete_c = 9;
  public static final int Corchete_a = 8;
  public static final int True = 62;
  public static final int Long = 18;
  public static final int Mul_igual = 57;
  public static final int Punto = 11;
  public static final int Default = 35;
  public static final int Punto_coma = 13;
  public static final int Char = 25;
  public static final int Decremento = 61;
  public static final int Asi_apu = 69;
  public static final int For = 36;
  public static final int Mayor_o_igual = 53;
  public static final int Void = 20;
  public static final int Else = 30;
  public static final int Resta = 41;
  public static final int Int = 15;
  public static final int Op_xor = 48;
  public static final int Suma = 40;
  public static final int Resta_igual = 56;
  public static final int Diferente_que = 52;
  public static final int Main = 3;
  public static final int string = 26;
  public static final int Do = 31;
  public static final int Signed = 22;
  public static final int Short = 19;
  public static final int Op_y = 45;
  public static final int Div_igual = 58;
  public static final int Case = 34;
  public static final int Op_o = 46;
  public static final int Unsi = 21;
  public static final int Numeral = 14;
  public static final int Ch = 75;
  public static final int If = 29;
  public static final int Define = 65;
  public static final int Igual_que = 51;
  public static final int EOF = 0;
  public static final int Real = 73;
  public static final int Numero = 72;
  public static final int Double = 16;
  public static final int Struct = 28;
  public static final int Division = 43;
  public static final int Op_negacion = 47;
  public static final int Dos_puntos = 12;
  public static final int error = 1;
  public static final int False = 63;
  public static final int Enum = 23;
  public static final int Float = 17;
  public static final int Menor_que = 50;
  public static final int Mod_igual = 59;
  public static final int Identificador = 70;
  public static final int Menor_o_igual = 54;
  public static final int O_bit = 67;
  public static final int Include = 64;
  public static final int Modulo = 44;
  public static final int Igual = 39;
  public static final int Goto = 38;
  public static final int Str = 74;
  public static final int While = 32;
  public static final int Union = 27;
  public static final int Boolean = 24;
  public static final int Multiplicacion = 42;
  public static final int Y_bit = 66;
  public static final int Switch = 33;
  public static final int Nul = 68;
}

